# netlify.toml
[[redirects]]
from = "/mapbox/*"
to = "https://api.mapbox.com/:splat"
status = 200
force = true

[[redirects]]
from = "/aws/*"
to = "https://sdk.amazonaws.com/:splat"
status = 200
force = true

[[headers]]
for = "/"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "**/*.wasm"
[headers.values]
Content-Type = "application/wasm"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "**/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"